### ISSUE TITLE
[ci] Visual regression result reporting

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1171]
The visual regression tests return their results in a somewhat dense log format.  A high level summary report would be extremely helpful.

Reference: https://github.com/patternfly/patternfly-elements/pull/1091/checks?check_run_id=1353643442

```
[0-0] RUNNING in chrome - /elements/pfe-accordion/test/pfe-accordion_e2e.js
[0-2] RUNNING in chrome - /elements/pfe-avatar/test/pfe-avatar_e2e.js
[0-1] RUNNING in chrome - /elements/pfe-autocomplete/test/pfe-autocomplete_e2e.js
[0-2] PASSED in chrome - /elements/pfe-avatar/test/pfe-avatar_e2e.js
[0-0] PASSED in chrome - /elements/pfe-accordion/test/pfe-accordion_e2e.js
[0-3] RUNNING in chrome - /elements/pfe-badge/test/pfe-badge_e2e.js
[0-4] RUNNING in chrome - /elements/pfe-band/test/pfe-band_e2e.js
[0-1] PASSED in chrome - /elements/pfe-autocomplete/test/pfe-autocomplete_e2e.js
[0-5] RUNNING in chrome - /elements/pfe-button/test/pfe-button_e2e.js
[0-3] PASSED in chrome - /elements/pfe-badge/test/pfe-badge_e2e.js
[0-6] RUNNING in chrome - /elements/pfe-card/test/pfe-card_e2e.js
[0-6] PASSED in chrome - /elements/pfe-card/test/pfe-card_e2e.js
[0-4] PASSED in chrome - /elements/pfe-band/test/pfe-band_e2e.js
[0-7] RUNNING in chrome - /elements/pfe-collapse/test/pfe-collapse_e2e.js
[0-8] RUNNING in chrome - /elements/pfe-content-set/test/pfe-content-set_e2e.js
[0-5] PASSED in chrome - /elements/pfe-button/test/pfe-button_e2e.js
[0-9] RUNNING in chrome - /elements/pfe-cta/test/pfe-cta_e2e.js
[0-7] PASSED in chrome - /elements/pfe-collapse/test/pfe-collapse_e2e.js
[0-10] RUNNING in chrome - /elements/pfe-datetime/test/pfe-datetime_e2e.js
[0-8] Error in "pfe-content-set should compare to the baseline"
Error: expect(received).toBeLessThan(expected)

Expected: < 1.25
Received:   5.14
    at Context.<anonymous> (/home/runner/work/patternfly-elements/patternfly-elements/elements/pfe-content-set/test/pfe-content-set_e2e.js:20:42)
[0-9] PASSED in chrome - /elements/pfe-cta/test/pfe-cta_e2e.js
[0-11] RUNNING in chrome - /elements/pfe-dropdown/test/pfe-dropdown_e2e.js
[0-8] FAILED in chrome - /elements/pfe-content-set/test/pfe-content-set_e2e.js
[0-12] RUNNING in chrome - /elements/pfe-health-index/test/pfe-health-index_e2e.js
[0-10] PASSED in chrome - /elements/pfe-datetime/test/pfe-datetime_e2e.js
[0-13] RUNNING in chrome - /elements/pfe-icon-panel/test/pfe-icon-panel_e2e.js
[0-12] PASSED in chrome - /elements/pfe-health-index/test/pfe-health-index_e2e.js
[0-14] RUNNING in chrome - /elements/pfe-icon/test/pfe-icon_e2e.js
[1-17] 2020-11-04T15:38:38.452Z ERROR webdriver: Request failed with status 500 due to Error: JavaScript error
[1-17] Error in "pfe-modal "before all" hook for "should take a screenshot""
Error: JavaScript error
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Context.<anonymous> (/home/runner/work/patternfly-elements/patternfly-elements/elements/pfe-modal/test/pfe-modal_e2e.js:6:13)
[1-17] FAILED in IE - /elements/pfe-modal/test/pfe-modal_e2e.js
[1-19] RUNNING in IE - /elements/pfe-number/test/pfe-number_e2e.js
[1-15] Error in "pfe-jump-links should compare to the baseline"
Error: expect(received).toBeLessThan(expected)

Expected: < 1.5
Received:   99.41
    at Context.<anonymous> (/home/runner/work/patternfly-elements/patternfly-elements/elements/pfe-jump-links/test/pfe-jump-links_e2e.js:14:42)
[1-15] FAILED in IE - /elements/pfe-jump-links/test/pfe-jump-links_e2e.js
[1-20] RUNNING in IE - /elements/pfe-page-status/test/pfe-page-status_e2e.js
[1-19] PASSED in IE - /elements/pfe-number/test/pfe-number_e2e.js
[1-21] RUNNING in IE - /elements/pfe-progress-indicator/test/pfe-progress-indicator_e2e.js
[1-18] Error in "pfe-navigation should compare to the baseline"
Error: expect(received).toBeLessThan(expected)

Expected: < 1.25
Received:   23.43
    at Context.<anonymous> (/home/runner/work/patternfly-elements/patternfly-elements/elements/pfe-navigation/test/pfe-navigation_e2e.js:14:42)
[1-18] FAILED in IE - /elements/pfe-navigation/test/pfe-navigation_e2e.js
[1-22] RUNNING in IE - /elements/pfe-select/test/pfe-select_e2e.js
[1-20] Error in "pfe-page-status should compare to the baseline"
Error: expect(received).toBeLessThan(expected)

Expected: < 1.25
Received:   2.51
    at Context.<anonymous> (/home/runner/work/patternfly-elements/patternfly-elements/elements/pfe-page-status/test/pfe-page-status_e2e.js:13:42)
[1-20] FAILED in IE - /elements/pfe-page-status/test/pfe-page-status_e2e.js
[1-23] RUNNING in IE - /elements/pfe-tabs/test/pfe-tabs_e2e.js
[1-21] PASSED in IE - /elements/pfe-progress-indicator/test/pfe-progress-indicator_e2e.js
[1-24] RUNNING in IE - /elements/pfe-toast/test/pfe-toast_e2e.js
[1-22] Error in "pfe-select should compare to the baseline"
Error: expect(received).toBeLessThan(expected)

Expected: < 1.5
Received:   4.29
    at Context.<anonymous> (/home/runner/work/patternfly-elements/patternfly-elements/elements/pfe-select/test/pfe-select_e2e.js:13:42)
[1-22] FAILED in IE - /elements/pfe-select/test/pfe-select_e2e.js
[1-23] Error in "pfe-tabs should compare to the baseline"
Error: expect(received).toBeLessThan(expected)

Expected: < 1.25
Received:   9.13
    at Context.<anonymous> (/home/runner/work/patternfly-elements/patternfly-elements/elements/pfe-tabs/test/pfe-tabs_e2e.js:13:42)
[1-23] FAILED in IE - /elements/pfe-tabs/test/pfe-tabs_e2e.js
[1-24] Error in "pfe-toast should compare to the baseline"
Error: expect(received).toBeLessThan(expected)

Expected: < 2.5
Received:   2.84
    at Context.<anonymous> (/home/runner/work/patternfly-elements/patternfly-elements/elements/pfe-toast/test/pfe-toast_e2e.js:17:42)
[1-24] FAILED in IE - /elements/pfe-toast/test/pfe-toast_e2e.js

Spec Files:	 26 passed, 24 failed, 50 total (100% completed) in 00:04:37 
```

**Comment by castastrophe** [comment]
Possible deliverable for this:

- Return a comment to a pull request with a list of any failing E2E tests and their environments.  Link to the artifact.
- Update the reporting summary to focus on the failed tests and not show every test that was run.
