### ISSUE TITLE
Docs folder and index.md missing on create-element

### ISSUE THREAD

**Issue by zeroedin** [patternfly/patternfly-elements#1908]
## Description of the issue

The `./elements/{{new-element}}/docs` folder is missing on `npm run new`, as well as the `index.md` file it should contain.  A basic `index.md` file would be helpful on initial component creation.  The following error will get thrown on `npm run watch:docs` otherwise:

```
 [ERROR] [plugin packageVersion] ENOENT: no such file or directory, open '/Users/sps/Sites/_pattern-fly/pfe2/core/pfe-core/functions/debounce.js'

    elements/pfe-primary-detail/pfe-primary-detail.ts:13:25:
      13 │ import { debounce } from '@patternfly/pfe-core/functions/debounce.js';
         ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/esbuild/lib/main.js:845:22:
      845 │         let promise = setup({
          ╵                       ^

    at setup (file:///Users/sps/Sites/_pattern-fly/pfe2/tools/pfe-tools/esbuild-plugins/package-version.js:24:19)
    at handlePlugins (/Users/sps/Sites/_pattern-fly/pfe2/node_modules/esbuild/lib/main.js:845:23)
    at Object.buildOrServe (/Users/sps/Sites/_pattern-fly/pfe2/node_modules/esbuild/lib/main.js:1139:7)
    at /Users/sps/Sites/_pattern-fly/pfe2/node_modules/esbuild/lib/main.js:2080:17
    at new Promise (<anonymous>)
    at Object.build (/Users/sps/Sites/_pattern-fly/pfe2/node_modules/esbuild/lib/main.js:2079:14)
    at Object.build (/Users/sps/Sites/_pattern-fly/pfe2/node_modules/esbuild/lib/main.js:1929:51)
    at bundle (/Users/sps/Sites/_pattern-fly/pfe2/docs/_plugins/bundle.cjs:33:19)
    at async AsyncEventEmitter.<anonymous> (/Users/sps/Sites/_pattern-fly/pfe2/docs/_plugins/pfe-assets.cjs:48:9)

[9:30:26 AM] @custom-elements-manifest/analyzer: Created new manifest.
1 error
```

### Impacted component(s)

- create-element script

### Steps to reproduce

1. `npm ci`
2. `npm run build -w @patternfly/create-element`
3. `npm run new`
4. complete create element wizard
5.  `npm run watch:docs`

### Expected behavior

Component folder should contain a `docs/` directory and it should contain a minimum `index.md` file.

Contents of `index.md` template could be minimal on initial create:

```
{% renderOverview %}
  <<%= tagName %>></<%= tagName %>>
{% endrenderOverview %}

{% band header="Usage" %}{% endband %}

{% renderSlots %}{% endrenderSlots %}

{% renderAttributes %}{% endrenderAttributes %}

{% renderMethods %}{% endrenderMethods %}

{% renderEvents %}{% endrenderEvents %}

{% renderCssCustomProperties %}{% endrenderCssCustomProperties %}

{% renderCssParts %}{% endrenderCssParts %}
```

**Comment by bennypowers** [comment]
closed by #1909
